name: Run Model Simulations

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      simulation_type:
        description: 'Type of simulation to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - agent-based
        - discrete-event
        - system-dynamics
        - integrated-multi-model
      case_id:
        description: 'Case ID for simulation'
        required: false
        default: 'case_2025_simulation_test'
        type: string

jobs:
  run-agent-based-simulation:
    if: github.event.inputs.simulation_type == 'agent-based' || github.event.inputs.simulation_type == 'all' || github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run Agent-Based Model Simulation (HyperGNN)
      run: |
        python scripts/run_agent_based_simulation.py \
          --case-id "${{ github.event.inputs.case_id || 'case_2025_simulation_test' }}" \
          --output-dir sims
          
    - name: Upload Agent-Based Simulation Results
      uses: actions/upload-artifact@v4
      with:
        name: agent-based-simulation-results
        path: sims/
        retention-days: 30

  run-discrete-event-simulation:
    if: github.event.inputs.simulation_type == 'discrete-event' || github.event.inputs.simulation_type == 'all' || github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run Discrete Event Model Simulation
      run: |
        python scripts/run_discrete_event_simulation.py \
          --case-id "${{ github.event.inputs.case_id || 'case_2025_simulation_test' }}" \
          --output-dir sims
          
    - name: Upload Discrete Event Simulation Results
      uses: actions/upload-artifact@v4
      with:
        name: discrete-event-simulation-results
        path: sims/
        retention-days: 30

  run-system-dynamics-simulation:
    if: github.event.inputs.simulation_type == 'system-dynamics' || github.event.inputs.simulation_type == 'all' || github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run System Dynamics Model Simulation
      run: |
        python scripts/run_system_dynamics_simulation.py \
          --case-id "${{ github.event.inputs.case_id || 'case_2025_simulation_test' }}" \
          --output-dir sims
          
    - name: Upload System Dynamics Simulation Results
      uses: actions/upload-artifact@v4
      with:
        name: system-dynamics-simulation-results
        path: sims/
        retention-days: 30

  run-integrated-multi-model-simulation:
    if: github.event.inputs.simulation_type == 'integrated-multi-model' || github.event.inputs.simulation_type == 'all' || github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run Integrated Multi-Model Simulation (HyperGNN + Case-LLM)
      run: |
        python scripts/run_integrated_simulation.py \
          --case-id "${{ github.event.inputs.case_id || 'case_2025_simulation_test' }}" \
          --output-dir sims
          
    - name: Upload Integrated Simulation Results
      uses: actions/upload-artifact@v4
      with:
        name: integrated-multi-model-simulation-results
        path: sims/
        retention-days: 30

  aggregate-results:
    if: github.event.inputs.simulation_type == 'all' || github.event_name != 'workflow_dispatch'
    needs: [run-agent-based-simulation, run-discrete-event-simulation, run-system-dynamics-simulation, run-integrated-multi-model-simulation]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all simulation results
      uses: actions/download-artifact@v4
      with:
        path: all-results/
        
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Generate Comprehensive Simulation Report
      run: |
        python scripts/generate_simulation_report.py \
          --results-dir all-results/ \
          --case-id "${{ github.event.inputs.case_id || 'case_2025_simulation_test' }}" \
          --output-dir sims
          
    - name: Upload Final Aggregated Results
      uses: actions/upload-artifact@v4
      with:
        name: comprehensive-simulation-report
        path: sims/
        retention-days: 90